config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %>
    <%= link_to t(".link"), "https://www.railstutorial.org/" %>
    <%= t ".by" %>
    <%= link_to t(".link_1"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
        <li><%= link_to t("english").html_safe, locale: "en" %></li>
        <li><%= link_to t("vietnamese").html_safe, locale: "vi" %></li>
        <li><%= link_to t("static_pages.about.title"), about_path %></li>
        <li><%= link_to t("static_pages.contact.title"), contact_path %></li>
        <li><%= link_to t(".link_2"), "http://news.railstutorial.org" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to t("SampleApp"), root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t("home"), root_path %></li>
            <li><%= link_to t("static_pages.help.title"), help_path %></li>
            <% if logged_in? %>
                <li><%= link_to t(".user"), users_path %></li>
                <li class="dropdown">
                    <%= link_to "#", class: "dropdown-toggle",
                        data: {toggle: "dropdown"} do %>
                        <%= t ".account" %>
                        <%= content_tag :b, "", class: "caret" %>
                    <% end %>
                    <ul class="dropdown-menu">
                    <li><%= link_to t(".profile"), current_user %></li>
                    <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to t(".logout"), logout_path, method: :delete %>
                    </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to t("login"), login_path %></li>
            <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    
    <%= render "layouts/shim" %>

    </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>